### ISSUE TITLE
Consider using wildcards for parameters and/or implement also multiparam support

### ISSUE THREAD

**Issue by Skylonxe** [getnamo/global-event-system-ue4#10]
Multiparameter events could be created by using special object as param (see JSON blueprint functions).

**Comment by getnamo** [comment]
I do want to support multi-param but I'm leaning toward maybe adding a macro type + button to add/remove wildcard params from the function. Haven't figured out the unreal code for that yet. In meantime a temporary solution is to wrap your multiparam data in a custom blueprint struct which should work.

**Comment by getnamo** [comment]
Added wildcard unbind event for cleanup for this feature at https://github.com/getnamo/global-event-system-ue4/commit/b57a0f5f4163b68db13aa11622250c175a79e69c

**Comment by getnamo** [comment]
Wildcard is currently supported.
Multi-param support will be tracked here: https://github.com/getnamo/global-event-system-ue4/issues/3

**Comment by getnamo** [comment]
Release: https://github.com/getnamo/global-event-system-ue4/releases/tag/0.7.0e
