### ISSUE TITLE
Question about Cross Map

### ISSUE THREAD

**Issue by HeadClot** [getnamo/global-event-system-ue4#12]
Hey @getnamo Got a question for you - What do you mean by "cross-map" with the Global event plugin? 

"Aims to solve cross-map and cross-blueprint communication for reliable and inferable event flow."

Just curious

**Comment by getnamo** [comment]
From one submap to another (streaming map) or dynamically loaded maps. Typically you can only reference both assets from the persistent map and the eye dropped won't work between maps for hard links.

**Comment by HeadClot** [comment]
Ah Ok, Makes sense. Thank you for the insight :)
