### ISSUE TITLE
Skipped listener due to function not having a matching signature.

### ISSUE THREAD

**Issue by visoredvisored** [getnamo/global-event-system-ue4#25]
I'm emitting an event in c++ +with:
```
FGESEmitContext GEContext;   
GEContext.Event = TEXT("TurnBegin");   
GEContext.WorldContext = this;   
FGESHandler::DefaultHandler()->EmitEvent(GEContext, Actor);
```
Actor is a UObject* (AActor*).
Binding an event with UObject as input to TurnBegin in blueprint with the GESBindEvent node. 
I get the warning "Skipped listener due to function not having a matching NumericProperty signature" and the event doesn't trigger. 
When I change the input from UObject to integer the event triggers and the input is a random integer.

**Comment by getnamo** [comment]
What does the bound receiver event look like?

**Comment by visoredvisored** [comment]
Attaching screenshots.
![Kuvatõmmis 2021-12-24 122700](https://user-images.githubusercontent.com/91389147/147344935-925b8fc2-0d98-4884-949e-375ad3a3f21c.png)
![Kuvatõmmis 2021-12-24 122715](https://user-images.githubusercontent.com/91389147/147344941-fcbe58cb-dfcb-4e90-bcc1-4688b26b9ac8.png)

**Comment by visoredvisored** [comment]
In FGESHandler::EmitEvent(const FGESEmitContext& EmitData, UObject* ParamData)
When checking for valid params:
if (FunctionHasValidParams(Listener.Function, FNumericProperty::StaticClass(), PropData, Listener))
		{
			Listener.ReceiverWCO->ProcessEvent(Listener.Function, (void*)&ParamWrapper);// PropData.PropertyPtr);
		}
I think FNumericProperty::StaticClass() should instead be FObjectProperty::StaticClass()? Seems to work as expected with this change.

**Comment by getnamo** [comment]
Yep, looks like a copy paste error, good catch. Make a pull request with change and I'll merge it

**Comment by visoredvisored** [comment]
Seems it's already correct in the master. Now I'm confused how I got the old version : ).

**Comment by getnamo** [comment]
Hah it did seem familiar, likely an older engine plugin release. Not sure if latest release had the patch or if I fixed it post.
