### ISSUE TITLE
Use case insensitive FName instead of FString

### ISSUE THREAD

**Issue by Skylonxe** [getnamo/global-event-system-ue4#7]

**Comment by getnamo** [comment]
Strings have more utility functions in bp and most users would end up using conversion nodes. I don't see an issue with having the wider scope of case sensitive domains and events.

That said maybe a better alternative could be to add a case insensitive option toggle in the global options where it would cast all strings to lowercase before adding to event chain. This way we'd keep the utility of strings and have the option for case insensitive if the project prefers it.
