### ISSUE TITLE
Namespace and event register UI (autocomplete)

### ISSUE THREAD

**Issue by Skylonxe** [getnamo/global-event-system-ue4#8]
One more possible improvement is to add Global Event System to project settings and create there nice UI for defining namespaces and event names. Then in Blueprint you would pick event and namespace from dropdown. Something very similar or same is used by gameplay tags system.

**Comment by getnamo** [comment]
A dropdown menu for domains would be a good dev ux. I wonder how complicated the project settings setup is in c++...

**Comment by Skylonxe** [comment]
If you inherit from UDeveloperSettings it will automatically detect your child class and create category for it in project settings. Then you just need to add there editable config UPROPERTY() variables. For custom UI it will be probably best to check how UI for Gameplay Tags works because it uses same hierarchical namespace system. Otherwise this can be probably useful: https://docs.unrealengine.com/en-US/Programming/Slate/DetailsCustomization/index.html

**Comment by getnamo** [comment]
Note to self: might be able to get some string auto-complete with (SSugestionBox)[https://docs.unrealengine.com/en-US/API/Runtime/Slate/Widgets/Input/SSuggestionTextBox/index.html], see e.g. https://github.com/EpicGames/UnrealEngine/blob/7d9919ac7bfd80b7483012eab342cb427d60e8c9/Engine/Source/Developer/SessionFrontend/Private/Widgets/Console/SSessionConsoleCommandBar.cpp#L31. It's unknown atm if it's possible to place this in the correct context without engine modification.

**Comment by getnamo** [comment]
https://github.com/getnamo/global-event-system-ue4/issues/19 should add the UX desired. May at a later date split it away from gameplay tag system, but it fills the need completely atm.

**Comment by getnamo** [comment]
Release: https://github.com/getnamo/global-event-system-ue4/releases/tag/0.7.0e

**Comment by getnamo** [comment]
Documentation: https://github.com/getnamo/global-event-system-ue4#gesemittagevent
