### ISSUE TITLE
Bind function which takes event as parameter 

### ISSUE THREAD

**Issue by Skylonxe** [getnamo/global-event-system-ue4#9]
Like any other delegate binding function.

**Comment by getnamo** [comment]
Great idea no reason to not have a variant of that type

**Comment by getnamo** [comment]
Specific delegates do not appear possible without defining them inside the binding function. May need to emit a wildcard property with bp conversions as option instead.

**Comment by getnamo** [comment]
With v0.3.1 (https://github.com/getnamo/global-event-system-ue4/commit/0c8aa5423d8dc24a3a2035f647d101c9fb04e4d3)

Wildcard event delegates are supported with bp autocast conversions.

e.g.
![WildcardEventDelegate](https://user-images.githubusercontent.com/542365/70207671-58694200-16e0-11ea-8377-3f899891d14a.PNG)

**Comment by getnamo** [comment]
the To String property cast will try to convert mismatched so you can preview what you're receiving before changing to match

**Comment by getnamo** [comment]
released in https://github.com/getnamo/global-event-system-ue4/releases/tag/0.4.0
